safe:        false
url: https://richard-towers.com

source:      .
destination: ./_site
plugins_dir: ./_plugins

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   date

plugins:
  - jekyll-feed

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  wrap: div
  line_numbers: inline
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: style
